-- Run as SYSADMIN.
-- This creates only the dedicated project warehouse, database, and schema.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS DELIVERY_DELAY_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

ALTER WAREHOUSE DELIVERY_DELAY_WH SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS DELIVERY_DELAY_DB;
CREATE SCHEMA IF NOT EXISTS DELIVERY_DELAY_DB.SILVER;

USE WAREHOUSE DELIVERY_DELAY_WH;
USE DATABASE DELIVERY_DELAY_DB;
USE SCHEMA SILVER;
