// Synthetic historical examples only; every object contains the 30 API features.
const base = {
  purchase_year: 2018,
  purchase_month: 6,
  purchase_day_of_week: 2,
  purchase_hour: 14,
  approval_delay_hours: 1.5,
  approval_timestamp_missing: false,
  promised_delivery_window_days: 20,
  customer_state: "SP",
  item_row_count: 1,
  distinct_product_count: 1,
  distinct_seller_count: 1,
  item_price_total: 89.9,
  freight_value_total: 14.5,
  product_weight_g_total: 750,
  product_volume_cm3_total: 1200,
  product_measurement_missing_item_count: 0,
  product_category_fallback_item_count: 0,
  primary_product_category: "health_beauty",
  primary_seller_state: "SP",
  payment_row_count: 1,
  distinct_payment_type_count: 1,
  payment_value_total: 104.4,
  max_payment_installments: 3,
  primary_payment_type: "credit_card",
  payment_data_missing: false,
  customer_geolocation_missing: false,
  seller_customer_distance_missing_count: 0,
  seller_customer_distance_km_min: 12.5,
  seller_customer_distance_km_mean: 12.5,
  seller_customer_distance_km_max: 12.5,
};

export const DEMO_ORDERS = [
  { ...base, order_id: "demo-order-001", customer_state: "SP", primary_seller_state: "SP", seller_customer_distance_km_max: 12.5 },
  { ...base, order_id: "demo-order-002", purchase_month: 7, customer_state: "RJ", primary_seller_state: "MG", item_row_count: 2, distinct_product_count: 2, item_price_total: 210, freight_value_total: 29, seller_customer_distance_km_max: 435 },
  { ...base, order_id: "demo-order-003", purchase_month: 8, customer_state: "BA", primary_seller_state: "SP", promised_delivery_window_days: 28, item_price_total: 460, freight_value_total: 38, seller_customer_distance_km_max: 1450 },
  { ...base, order_id: "demo-order-004", purchase_month: 5, customer_state: "PR", primary_seller_state: "SC", approval_delay_hours: null, approval_timestamp_missing: true, payment_value_total: 75, seller_customer_distance_km_max: 310 },
  { ...base, order_id: "demo-order-005", purchase_month: 4, customer_state: "AM", primary_seller_state: "SP", approval_delay_hours: 72, promised_delivery_window_days: 5, item_row_count: 3, distinct_product_count: 2, distinct_seller_count: 2, item_price_total: 1000, freight_value_total: 100, seller_customer_distance_km_min: 3000, seller_customer_distance_km_mean: 3200, seller_customer_distance_km_max: 3398 },
  { ...base, order_id: "demo-order-006", purchase_month: 9, customer_state: "RS", primary_seller_state: "RS", product_weight_g_total: null, product_volume_cm3_total: null, product_measurement_missing_item_count: 1, seller_customer_distance_km_max: 55 },
  { ...base, order_id: "demo-order-007", purchase_month: 3, customer_state: "GO", primary_seller_state: "SP", item_row_count: 2, distinct_seller_count: 2, payment_row_count: 2, distinct_payment_type_count: 2, payment_value_total: 305, seller_customer_distance_km_max: 980 },
  { ...base, order_id: "demo-order-008", purchase_month: 10, customer_state: "PE", primary_seller_state: "PE", promised_delivery_window_days: 15, item_price_total: 42, freight_value_total: 9, seller_customer_distance_km_max: 8 },
];
